### PR TITLE
format and prof

### PR DESCRIPTION
**Pull request by OliverChao**
1. format all lua files using default stylua
2. there is no need of deep_equal check 
3. remove all deprecated api methods

### CODE REVIEW

**Comment by OliverChao** [comment]
There seems my own need for that and has some problems.

**Comment by ariel-frischer** [comment]
Interesting PR, I like the idea for the new `:BmessagesEdit` command. I think the `deep_equal ` check is  needed, when autoscroll is enabled, otherwise you get some annoying cursor movement.

**Comment by OliverChao** [comment]
Yep, autoscroll is what I say the problem.
I think there is one potential prof question when the message is so large if using `deep_equal`.
I just add one small optimization for that currently.

**Comment by ariel-frischer** [comment]
LGTM, my formatter is called with `:lua vim.lsp.buf.format({timeout_ms = 4000})` not sure what it uses in background (I think I'm using lual-ls) as the formatter but if the default is stylua I'm happy to work with it and set it up so there is some normalization.

**Pull request merged**
